<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="micromouse">

  <!-- ========= Parameters ========= -->
  <xacro:property name="wheel_radius" value="0.03"/>
  <xacro:property name="wheel_separation" value="0.08"/> <!-- distance between left & right wheels -->
  <xacro:property name="wheel_length" value="0.02"/>
  <xacro:property name="robot_length" value="0.12"/>
  <xacro:property name="robot_width" value="0.10"/>
  <xacro:property name="sensor_range" value="0.10"/>

  <!-- ========= Base Link ========= -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${robot_length} ${robot_width} 0.04"/>
      </geometry>
      <material name="Blue"/>
    </visual>
    <collision>
      <geometry>
        <box size="${robot_length} ${robot_width} 0.04"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.5"/>
      <inertia ixx="0.001" iyy="0.001" izz="0.001"/>
    </inertial>
  </link>

  <!-- ========= Wheels ========= -->
  <!-- Left Wheels -->
  <xacro:macro name="wheel" params="name x y z">
    <link name="${name}">
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
        <material name="Black"/>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.05"/>
        <inertia ixx="0.0001" iyy="0.0001" izz="0.0001"/>
      </inertial>
    </link>

    <joint name="${name}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${name}"/>
      <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <!-- Left wheels -->
  <xacro:wheel name="wheel_left_front" x="0.03" y="${wheel_separation/2}" z="-0.02"/>
  <xacro:wheel name="wheel_left_back" x="-0.03" y="${wheel_separation/2}" z="-0.02"/>
  <!-- Right wheels -->
  <xacro:wheel name="wheel_right_front" x="0.03" y="-${wheel_separation/2}" z="-0.02"/>
  <xacro:wheel name="wheel_right_back" x="-0.03" y="-${wheel_separation/2}" z="-0.02"/>

  <!-- ========= IR Sensors (Ray Sensors) ========= -->
  <xacro:macro name="ir_sensor" params="name x y yaw">
    <link name="${name}">
      <visual>
        <geometry>
          <cylinder radius="0.005" length="0.02"/>
        </geometry>
        <material name="Red"/>
      </visual>
    </link>

    <joint name="${name}_joint" type="fixed">
      <parent link="base_link"/>
      <child link="${name}"/>
      <origin xyz="${x} ${y} 0.02" rpy="0 0 ${yaw}"/>
    </joint>
  </xacro:macro>

  <!-- Front Sensors -->
  <xacro:ir_sensor name="ir_front" x="0.06" y="0" yaw="0"/>
  <xacro:ir_sensor name="ir_front_left" x="0.05" y="0.03" yaw="0.785"/> <!-- 45 deg -->
  <xacro:ir_sensor name="ir_front_right" x="0.05" y="-0.03" yaw="-0.785"/> <!-- -45 deg -->
  <!-- Side Sensors -->
  <xacro:ir_sensor name="ir_left" x="0" y="0.05" yaw="1.57"/> <!-- 90 deg -->
  <xacro:ir_sensor name="ir_right" x="0" y="-0.05" yaw="-1.57"/> <!-- -90 deg -->

  <!-- ========= Transmission & Diff Drive Plugin ========= -->
  <gazebo>
    <plugin name="diff_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <ros>
        <namespace>/</namespace>
        <remapping>cmd_vel:=/cmd_vel</remapping>
      </ros>
      <updateRate>100.0</updateRate>
      <wheelSeparation>${wheel_separation}</wheelSeparation>
      <wheelDiameter>${wheel_radius*2}</wheelDiameter>
      <leftJoint>wheel_left_front</leftJoint>
      <rightJoint>wheel_right_front</rightJoint>
      <leftJoint>wheel_left_back</leftJoint>
      <rightJoint>wheel_right_back</rightJoint>
      <robotBaseFrame>base_link</robotBaseFrame>
    </plugin>
  </gazebo>

</robot>
